// 용어 사전: 정답에 매칭되면 풀네임(full)과 설명(desc)을 결과 화면에 표시
// 키는 문제의 정답(q.a) 또는 빈칸 정답과 매칭됨. 없으면 문제 지문이 설명으로 대체됨.
const GLOSSARY = {
  // ── 웹 서비스 / SQL ──
  "UDDI": { full:"Universal Description, Discovery and Integration", desc:"웹 서비스의 등록과 검색을 위한 표준 저장소(레지스트리). 서비스 제공자가 WSDL을 등록하고, 요청자가 이를 검색해 서비스를 찾는다." },
  "WSDL": { full:"Web Services Description Language", desc:"웹 서비스의 인터페이스(서비스명·제공 위치·메시지 포맷·프로토콜)를 기술한 XML 기반 언어." },
  "SOAP": { full:"Simple Object Access Protocol", desc:"HTTP·SMTP 등을 이용해 XML 기반 메시지를 교환하는 웹 서비스 통신 프로토콜." },
  "SQL": { full:"Structured Query Language", desc:"관계형 데이터베이스에 데이터를 정의·조작·제어하기 위한 구조화 질의 언어. 최초는 IBM System R." },
  "DDL": { full:"Data Definition Language", desc:"DB 객체의 구조를 정의하는 언어. CREATE·ALTER·DROP·TRUNCATE." },
  "DML": { full:"Data Manipulation Language", desc:"데이터를 조작(검색·삽입·수정·삭제)하는 언어. SELECT·INSERT·UPDATE·DELETE." },
  "DCL": { full:"Data Control Language", desc:"DB 접근 권한을 제어하는 언어. GRANT(부여)·REVOKE(회수)." },
  "TCL": { full:"Transaction Control Language", desc:"트랜잭션을 제어하는 언어. COMMIT·ROLLBACK·SAVEPOINT." },
  "ACID": { full:"Atomicity, Consistency, Isolation, Durability", desc:"트랜잭션이 보장해야 할 4대 특성: 원자성·일관성·격리성·지속성." },
  "BCNF": { full:"Boyce-Codd Normal Form", desc:"제3정규형을 만족하면서 모든 결정자가 후보키가 되도록 강화한 정규형." },

  // ── 비용/방법론 ──
  "COCOMO": { full:"COnstructive COst MOdel", desc:"보헴이 제안한 비용 산정 모형. 프로그램 규모(LoC)에 따라 조직형·반분리형·임베디드형으로 산정." },
  "LOC": { full:"Lines of Code", desc:"원시 코드 라인 수의 낙관치·중간치·비관치로 예측치를 구해 비용을 산정하는 상향식 기법." },
  "XP": { full:"eXtreme Programming", desc:"짧은 개발 주기와 강한 피드백을 강조하는 애자일 방법론. 5가지 가치: 피드백·존중·의사소통·용기·단순성." },
  "TDD": { full:"Test-Driven Development", desc:"테스트를 먼저 작성하고 이를 통과하는 코드를 구현하는 개발 기법(RED→GREEN→REFACTOR)." },
  "CMMI": { full:"Capability Maturity Model Integration", desc:"카네기멜런 SEI의 프로세스 성숙도 모델. 초기→관리→정의→정량적 관리→최적화의 5단계." },
  "SAAM": { full:"Software Architecture Analysis Method", desc:"시나리오 기반으로 소프트웨어 아키텍처를 분석·평가하는 방법론." },
  "ATAM": { full:"Architecture Tradeoff Analysis Method", desc:"여러 품질 속성 간의 상충(trade-off) 관계를 분석해 아키텍처를 평가하는 방법론." },
  "CBAM": { full:"Cost Benefit Analysis Method", desc:"비용 대비 편익을 분석해 아키텍처 대안을 평가하는 방법론." },
  "UML": { full:"Unified Modeling Language", desc:"객체지향 시스템을 표현하는 표준 모델링 언어. 구조 다이어그램과 행위 다이어그램으로 나뉜다." },

  // ── 서버/인터페이스 ──
  "IPC": { full:"Inter-Process Communication", desc:"프로세스(모듈) 간 데이터를 주고받는 통신. Shared Memory·Socket·Semaphore·Pipe·Message Queue." },
  "SOLID": { full:"SRP·OCP·LSP·ISP·DIP", desc:"객체지향 설계 5대 원칙: 단일책임·개방폐쇄·리스코프치환·인터페이스분리·의존역전." },
  "SRP": { full:"Single Responsibility Principle", desc:"단일 책임 원칙. 클래스는 오직 하나의 책임만 가져야 한다." },
  "OCP": { full:"Open-Closed Principle", desc:"개방-폐쇄 원칙. 확장에는 열려 있고 변경에는 닫혀 있어야 한다." },
  "LSP": { full:"Liskov Substitution Principle", desc:"리스코프 치환 원칙. 자식 클래스는 언제나 부모 클래스를 대체할 수 있어야 한다." },
  "ISP": { full:"Interface Segregation Principle", desc:"인터페이스 분리 원칙. 사용하지 않는 인터페이스에 의존하지 않아야 한다." },
  "DIP": { full:"Dependency Inversion Principle", desc:"의존 역전 원칙. 구체 클래스보다 추상(인터페이스)에 의존해야 한다." },
  "EAI": { full:"Enterprise Application Integration", desc:"기업 내 애플리케이션을 통합·연계하는 솔루션. Point-to-Point·Hub&Spoke·Message Bus·Hybrid 유형." },
  "ESB": { full:"Enterprise Service Bus", desc:"SOA를 지원하며 애플리케이션 간 통신을 버스 형태로 중계·통합하는 미들웨어." },
  "REST": { full:"REpresentational State Transfer", desc:"HTTP 기반으로 URI로 자원을 표현하고 GET·POST·PUT·DELETE로 CRUD를 수행하는 아키텍처." },
  "JSON": { full:"JavaScript Object Notation", desc:"속성-값(key-value) 쌍으로 구성된 경량 데이터 교환 형식." },
  "AJAX": { full:"Asynchronous JavaScript And XML", desc:"전체 페이지 새로고침 없이 비동기로 필요한 부분만 갱신하는 웹 통신 기술." },
  "MVC": { full:"Model-View-Controller", desc:"애플리케이션을 데이터(Model)·화면(View)·제어(Controller)로 분리하는 아키텍처 패턴." },
  "DAO": { full:"Data Access Object", desc:"데이터베이스 접근(CRUD)을 전담하도록 설계한 객체." },
  "DTO": { full:"Data Transfer Object", desc:"계층 간 데이터 전송을 위해 사용하는 객체(=VO, Value Object)." },

  // ── 보안: 관리/저작권 ──
  "DRM": { full:"Digital Rights Management", desc:"디지털 콘텐츠의 생성~유통~사용 전 과정에서 저작권과 사용 범위를 통제·보호하는 기술." },
  "INDECS": { full:"Interoperability of Data in E-Commerce Systems", desc:"전자상거래에서 디지털 콘텐츠 저작권 보호를 위해 메타데이터를 통일한 프레임워크(DRM과 구분)." },
  "ISMS": { full:"Information Security Management System", desc:"정보자산을 안전하게 관리하기 위한 정보보호 관리체계. 목표: 기밀성·무결성·가용성." },
  "PIMS": { full:"Personal Information Management System", desc:"개인정보를 안전하게 다루기 위해 구축한 개인정보보호 관리체계." },
  "DLP": { full:"Data Loss/Leakage Prevention", desc:"조직 내부 정보의 외부 유출을 방지하는 대책(접근통제·암호화·필터링·감시)." },
  "RPO": { full:"Recovery Point Objective", desc:"재해 시 허용 가능한 데이터 손실 시점(복구 목표 시점). '얼마 전 데이터까지 복구'." },
  "RTO": { full:"Recovery Time Objective", desc:"재해로 중단된 업무를 복구하는 데까지 허용되는 목표 시간. '얼마 만에 복구'." },
  "DRP": { full:"Disaster Recovery Plan", desc:"재난에 대비해 H/W·S/W 복구 계획을 미리 마련하는 것." },
  "IAM": { full:"Identity and Access Management", desc:"구성원의 신분을 확인하고 자원 접근을 제어하는 계정 접근 관리 시스템." },
  "OWASP": { full:"Open Web Application Security Project", desc:"웹 애플리케이션의 대표 취약점 10가지(Top 10) 등을 발표하는 오픈 보안 단체." },
  "CAPTCHA": { full:"Completely Automated Public Turing test to tell Computers and Humans Apart", desc:"등록자가 사람인지 컴퓨터인지 판별하는 자동 계정 생성 방지 기술." },
  "C4I": { full:"Command, Control, Communication, Computer & Intelligence", desc:"군의 전 자원을 전산화·네트워크화한 통합 전장 관리 체계." },

  // ── 보안: 공격 ──
  "APT": { full:"Advanced Persistent Threat", desc:"특정 대상을 장기간 지속적·지능적으로 공격해 정보를 수집·탈취하는 지능형 지속 위협." },
  "DoS": { full:"Denial of Service", desc:"시스템이 정상 서비스를 제공하지 못하도록 자원을 고갈시키는 서비스 거부 공격." },
  "DDoS": { full:"Distributed Denial of Service", desc:"분산된 다수의 좀비 PC가 동시에 한 서버를 공격하는 분산 서비스 거부 공격." },
  "XSS": { full:"Cross-Site Scripting", desc:"웹 페이지에 악성 스크립트를 삽입해 피해자(클라이언트) 브라우저에서 실행시키는 공격." },
  "CSRF": { full:"Cross-Site Request Forgery", desc:"로그인된 사용자의 권한을 도용해 사용자 의지와 무관하게 서버에 요청을 보내는 공격." },
  "SSRF": { full:"Server-Side Request Forgery", desc:"서버를 속여 내부 시스템이나 다른 서버로 요청을 보내게 해 내부 정보를 탐색·탈취하는 공격." },
  "TOCTOU": { full:"Time-Of-Check To Time-Of-Use", desc:"검사 시점과 사용 시점 사이의 타이밍(경쟁 조건)을 노리는 공격." },
  "MITM": { full:"Man-In-The-Middle", desc:"통신하는 두 당사자 사이에 끼어들어 정보를 도청·조작하는 중간자 공격." },

  // ── 보안: 방어 솔루션 ──
  "VPN": { full:"Virtual Private Network", desc:"공중망에 암호화·터널링을 적용해 전용 회선처럼 사용하는 가상 사설망." },
  "IPSec": { full:"IP Security", desc:"IP 계층에서 무결성·인증(AH)과 기밀성(암호화)을 보장하는 IP 보안 프로토콜." },
  "SSL": { full:"Secure Sockets Layer", desc:"전송·응용 계층 사이에서 데이터 암호화·인증·무결성을 보장하는 프로토콜(HTTPS 기반)." },
  "TLS": { full:"Transport Layer Security", desc:"SSL의 후속 표준. 전송 구간 암호화·인증으로 안전한 통신을 제공." },
  "WAF": { full:"Web Application Firewall", desc:"HTTP/HTTPS 트래픽을 검사해 SQL 인젝션·XSS 등 웹 공격을 차단하는 웹 방화벽." },
  "IDS": { full:"Intrusion Detection System", desc:"네트워크 이벤트를 모니터링해 침입을 실시간 탐지하고 경고하는 시스템(차단은 X)." },
  "IPS": { full:"Intrusion Prevention System", desc:"침입을 탐지할 뿐 아니라 자동으로 차단까지 수행하는 시스템(IDS 기능 포함)." },
  "NAC": { full:"Network Access Control", desc:"단말이 네트워크 접속 전 보안 정책 준수 여부를 검사해 접근을 통제하는 솔루션." },
  "UTM": { full:"Unified Threat Management", desc:"방화벽·IDS/IPS·안티바이러스 등을 하나의 장비로 통합한 통합 보안 시스템." },
  "ESM": { full:"Enterprise Security Management", desc:"방화벽·IDS·VPN 등 여러 보안 솔루션을 하나로 모아 관리하는 통합 보안 관리 시스템." },
  "DMZ": { full:"Demilitarized Zone", desc:"내부망과 외부망 사이의 완충 영역. 외부 공개 서버를 두어 내부망을 보호한다." },
  "WIPS": { full:"Wireless Intrusion Prevention System", desc:"무선 단말의 접속을 탐지하고 비인가 무선 접속을 차단하는 무선 침입 방지 시스템." },

  // ── 보안: 암호 ──
  "DES": { full:"Data Encryption Standard", desc:"1975년 미국(NBS)이 발표한 대칭키 블록 암호. 이를 3번 적용한 3DES도 있음." },
  "3DES": { full:"Triple DES", desc:"DES 암호화를 3번 적용해 안전성을 높인 대칭키 블록 암호." },
  "AES": { full:"Advanced Encryption Standard", desc:"2001년 미국(NIST)이 DES를 대체하기 위해 공모·발표한 대칭키 블록 암호." },
  "SEED": { full:"KISA 개발 국산 블록 암호", desc:"한국인터넷진흥원(KISA)이 개발한 128비트 대칭키 블록 암호 알고리즘." },
  "ARIA": { full:"Academy, Research Institute, Agency", desc:"2004년 국가정보원과 산학연구협회가 개발한 국산 대칭키 블록 암호(개발 주체 이니셜)." },
  "IDEA": { full:"International Data Encryption Algorithm", desc:"DES를 대체하기 위해 스위스에서 개발한 대칭키 블록 암호." },
  "RSA": { full:"Rivest-Shamir-Adleman", desc:"1978년 MIT 3인이 제안한 공개키 암호. 큰 수의 소인수분해가 어렵다는 점에 기반." },
  "ECC": { full:"Elliptic Curve Cryptography", desc:"타원 곡선을 이용한 공개키 암호. RSA의 대안으로 짧은 키로 강한 보안을 제공." },
  "LEA": { full:"Lightweight Encryption Algorithm", desc:"국내 개발 경량 고속 블록 암호. AES보다 약 2배 빠름." },
  "RC4": { full:"Rivest Cipher 4", desc:"바이트 단위로 처리하는 대표적 스트림 암호(대칭키)." },
  "LFSR": { full:"Linear Feedback Shift Register", desc:"선형 되먹임 시프트 레지스터를 이용한 스트림 암호화 방식." },
  "MD5": { full:"Message-Digest algorithm 5", desc:"R.Rivest가 MD4를 대체하려 고안한 해시 함수(블록 512비트, 무결성 검사에 사용)." },
  "SHA-1": { full:"Secure Hash Algorithm 1", desc:"NSA가 설계하고 미 정부 표준으로 지정한 해시 알고리즘." },
  "HAS-160": { full:"국산 표준 서명용 해시", desc:"국내 표준 전자서명을 위해 MD5와 SHA-1의 장점을 결합해 개발한 해시 함수." },
  "DAC": { full:"Discretionary Access Control", desc:"임의적 접근 통제. 정보 소유자가 재량으로 접근 권한을 부여한다." },
  "MAC": { full:"Mandatory Access Control", desc:"강제적 접근 통제. 중앙에서 보안 등급을 정해 정책적으로 접근을 통제한다(군사용)." },
  "RBAC": { full:"Role-Based Access Control", desc:"역할 기반 접근 통제. 사람이 아닌 직책(역할)에 권한을 부여한다." },

  // ── 운영체제 / 네트워크 ──
  "OSI": { full:"Open Systems Interconnection", desc:"국제표준 네트워크 7계층 모델: 물리-데이터링크-네트워크-전송-세션-표현-응용." },
  "TCP": { full:"Transmission Control Protocol", desc:"연결형·신뢰성 전송 계층 프로토콜. 데이터를 보낸 순서대로 전달함을 보장." },
  "UDP": { full:"User Datagram Protocol", desc:"비연결형·고속 전송 계층 프로토콜. checksum으로 손상 정보만 제공." },
  "DNS": { full:"Domain Name System", desc:"문자 도메인 네임을 컴퓨터가 이해하는 IP 주소로 변환하는 시스템." },
  "OSPF": { full:"Open Shortest Path First", desc:"링크 상태 기반으로 최단 경로를 계산하는 내부 라우팅 프로토콜." },
  "LRU": { full:"Least Recently Used", desc:"가장 오래 참조되지 않은 페이지를 교체. 카운터(타임스탬프)나 스택으로 구현." },
  "NUR": { full:"Not Used Recently", desc:"참조 비트·변형 비트(하드웨어 비트 2개)로 최근 사용 여부를 판단해 페이지를 교체." },
  "FIFO": { full:"First In First Out", desc:"메모리에 가장 먼저 들어온 페이지를 먼저 교체하는 가장 단순한 알고리즘." },
  "IPv6": { full:"Internet Protocol version 6", desc:"128비트 주소 공간. 인증성·기밀성·무결성 지원, 주소 자동 설정(IPv4는 32비트)." },

  // ── 제품 패키징 ──
  "Git": { full:"분산 버전 관리 시스템", desc:"리눅스 커널 개발용으로 만든 분산 VCS. 로컬 저장소에서 관리 후 중앙에 Push." },
  "SVN": { full:"Subversion", desc:"CVS를 개선한 중앙 집중형 버전 관리 시스템. 로그·롤백 지원." },
  "CVS": { full:"Concurrent Versions System", desc:"서버-클라이언트 구조의 초기 중앙 집중형 버전 관리 도구." },
};
